### ISSUE TITLE
Non Axis RTSP feed in React

### ISSUE THREAD

**Issue by mmeyers-solartech** [AxisCommunications/media-stream-player-js#15]
Hi there, me again. This question may be a bit in depth. 

Essentially I want to use this library to play my RTSP stream, the only difference is that I'm restreaming the RTSP feed from AXIS via VLC. Will this library allow me to play that RTSP feed rather than accessing an Axis feed directly? 

So using VLC I'm turning this feed rtsp://user:pw@IP/axis-media/media.amp?videocodec=h264 into a stream from VLC that looks like this: rtsp://127.0.0.1/stream

I notice the library does quite a bit of verification against the VAPIX params as well as appends all that axis-media detail to the URL. If I customized how that URL is generated would it play? The RTSP streams are the same, I can open up both in VLC to view and its not transcoded at all. 

Thanks

**Comment by mmeyers-solartech** [comment]
For clarification, when I change to a non Axis feed when passing a hostname I get this as a react failure:
SyntaxError: An invalid or illegal string was specified
onLoadToken
/lib/components/ws-source/openwebsocket.ts:74

  71 |         request.send();
  72 |     }
  73 |     catch (error) {
> 74 |         reject(originalError);
     | ^  75 |     }
  76 | };
  77 | ws.onopen = () => {

**Comment by steabert** [comment]
This library is mainly aimed towards using it with Axis cameras directly, but it's absolutely possible to adapt it to your needs. Since we need access to the RTSP stream in a browser, it needs to be tunneled through a WebSocket connection. If you provide your own RTSP stream, you also need to provide a WebSocket proxy that will forward the RTSP stream.

In the `PlaybackArea.tsx` file we build the `ws` and `rtsp` strings as need for an Axis camera, you can override the `wsUri` and `rtspUri` functions to return the URIs that you have.
