### ISSUE TITLE
Uncaught TypeError: Cannot read property 'videocodec' of null

### ISSUE THREAD

**Issue by rlueder** [AxisCommunications/media-stream-player-js#8]
**Describe the bug**
When following the example for integrating with React on [App.jsx](https://github.com/AxisCommunications/media-stream-player-js/blob/master/examples/react-app/App.jsx), I'm getting the following error:

`Uncaught TypeError: Cannot read property 'videocodec' of null`

As the error message states and looking at the paremeters expected by the [PlaybackArea](https://github.com/AxisCommunications/media-stream-player-js/blob/master/lib/PlaybackArea.tsx) component I was able to fix it by replacing the `format` parameter with `videocodec` instead:

```
<Player
    autoPlay
    hostname={state.hostname}
    vapixParams={vapixParams}
    // format="H264" - doesn't work, use videocodec instead
    videocodec="h264" 
/>
``` 
**To Reproduce**

Run the react-app example as it is.

**Comment by lekoaf** [comment]
Yes, I belive this happens when you change between formats that supports the videocodec paramater (h264 and mjpeg) and still image, which doesnt support it. No workaround should be needed. The issue should be fixed.

**Comment by steabert** [comment]
The reason `format` is used and not `videocodec` is that the latter is just the VAPIX parameter, while the former will also switch the API for you (and choose the proper accompanying display component).

VAPIX parameters that are not recognized are just ignored, so that shouldn't be the problem either.

Which line does the error occur on? Isn't is just `vapixParams` that is `null` somehow instead of `{}`?

**Comment by ErikMN** [comment]
I have the same problem when using the React example, when uncommenting format="H264" the video shows up but when I click the settings-cogwheel I get:
Uncaught TypeError: Cannot read property 'resolution' of null
